# db username and password (secret data)
apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
type: Opaque
stringData:
  PGHOST: lab-manager-dbs.postgres.database.azure.com
  PGUSER: user
  PGPORT: "5432"
  PGDATABASE: users-db
  PGPASSWORD: Geslo123
